spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: bigben
    driverClassName: com.mysql.cj.jdbc.Driver
  cache:
    type: redis

logging:
  level:
    com.github.lazyben.accounting: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  time-to-live: 5000